<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-20T16:51:41 IST" name="Default suite" finished-at="2022-10-20T16:51:51 IST" duration-ms="10164">
    <groups>
    </groups>
    <test started-at="2022-10-20T16:51:41 IST" name="Default test" finished-at="2022-10-20T16:51:51 IST" duration-ms="10164">
      <class name="saurabh.CreateNewAccountTest">
        <test-method is-config="true" signature="url()[pri:0, instance:saurabh.CreateNewAccountTest@15bbf42f]" started-at="2022-10-20T16:51:41 IST" name="url" finished-at="2022-10-20T16:51:51 IST" duration-ms="9686" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- url -->
        <test-method signature="LoginWithSignUP()[pri:0, instance:saurabh.CreateNewAccountTest@15bbf42f]" started-at="2022-10-20T16:51:51 IST" name="LoginWithSignUP" finished-at="2022-10-20T16:51:51 IST" duration-ms="396" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Facebook – log in or sign up]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Facebook – log in or sign up
at dev.failsafe.internal.util.Assert.state(Assert.java:40)
at saurabh.CreateNewAccountTest.LoginWithSignUP(CreateNewAccountTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithSignUP -->
      </class> <!-- saurabh.CreateNewAccountTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
